pepper_ips:
  - 130.239.182.11
  - 192.168.10.2
  - 192.168.10.3
  - 192.168.10.4

messages: 
  # Avoid special characters in messages, this can break the backend.
  # EG: Instead if a ', put &apos; into the message, which is the HTML symbol for the apostroph
  -
    short: Title # This will be shown in the GUI
    full_text: This is the complete message that we want the pepper robot to say. # This will be the spoken message
  -
    short: Hello
    full_text: Hello, Im pepper.
  -
    short: Insult
    full_text: Here are the test results; you are a horrible person.
  -
    short: Compliment
    full_text: Ive always thought you are virtually perfect.
  -
    short: Blah
    full_text: blah blah blah blah blah, blah blah blah, blah.

image_root_location: /static/imgs/  # place image files here, on host machine

images:
  -
    title: Default img
    file_name: climate_change.jpg
    is_default_img: True  # image with this flag will be displayed on connect
  - 
    title: Landscape
    file_name: landscape.jpg
  -
    title: Umea logo
    file_name: umea_logo.png
  -
    title: Arrow keys
    file_name: arrow_keys.png
  - 
    title: Sound playing
    file_name: sound_playing.png

audio_files:
  # These have to be stored directly on the Pepper, it's the only way properly supported by the naoqi API :/
  # Button will be created for every item in the list
  -
    title: Imperial March
    location: /home/nao/sound_files/ImperialMarch60.wav  # absolute path on the Pepper
  - 
    title: Cantina band
    location: /home/nao/sound_files/CantinaBand60.wav
  -
    title: Star Wars
    location: /home/nao/sound_files/StarWars60.wav
  - 
    title: Pink Panther
    location: /home/nao/sound_files/PinkPanther60.wav
  -
    title: Elephant walking
    location: /home/nao/sound_files/BabyElephantWalk60.wav

animated_speech:
    # Button will be created for every item in the list
  -
    title: Over here
    string: "Hello! ^start(animations/Stand/Gestures/Hey_1) I am over here. ^wait(animations/Stand/Gestures/Hey_1)"
    tooltip: blah
  -
    title: I am this tall
    string: "Look at me! ^run(animations/Stand/Gestures/ShowSky_8) I am this tall!"
    tooltip: blah
  -
    title: Point far
    string: "^start(animations/Stand/Gestures/Far_3) Theyre taking the hobbits to Isengard! ^wait(animations/Stand/Gestures/Far_3) "
    tooltip: blah
  -
    title: Show tablet
    string: "^start(ShowTablet_3) Look at my tablet. ^wait(ShowTablet_3)"
    tooltip: blah

gestures:
    # Button will be created for every item in the list
  -
    title: "Yes"
    string: "animations/Stand/Gestures/Yes_1"
    tooltip: blah
  -
    title: No
    string: "animations/Stand/Gestures/No_1"
    tooltip: blah
  -
    title: Wave
    string: "animations/Stand/Gestures/Hey_3"
    tooltip: blah
  -
    title: Me
    string: "animations/Stand/Gestures/Me_1"
    tooltip: blah
  -
    title: You
    string: "animations/Stand/Gestures/You_1"
    tooltip: blah
  -
    title: Embarrassed
    string: "animations/Stand/Emotions/Neutral/Embarrassed_1"
    tooltip: blah
  -
    title: Happy
    string: "animations/Stand/Emotions/Positive/Happy_4"
    tooltip: blah

camera_save_dir: record_imgs  # relative folder on host machine, images form camera feed will be saved here
audio_save_dir: /home/nao/ # absolute path on pepper robot, you'll have scp it from there yourself

# AUTONOMOUS LIFE SETTINGS
# Leave as empty string to not leave value as is on connection to robot
# values must be valid for respective set methods in naoqi API...
autonomous_life_config:
  autonomous_state: "solitary"
  tangential_collision: ""
  orthogonal_collision: ""
  blinking: False  # can interfere with manual eye control...
  basic_awareness: False  # gets enabled by default if pepper enters solitary or interactive state...
  engagement_mode: ""
  head_breathing: False  # I would advise always having this disabled, conflicts with manual head control...
  arms_breathing: True
  body_breathing: True
  legs_breathing: True

# LED SETTINGS
# Putting empty strings as values leave the settings as is on connect
led_settings:
  intensity: 0.1
  color: # color for eye leds. API requires rgb values in range [0-1]
    red: 0
    green: 1.0
    blue: 0