messages: 
  # Avoid special characters in messages, this can break the backend.
  # EG: Instead if a ', put &apos; into the message, which is the HTML symbol for the apostroph
  -
    short: Title # This will be shown in the GUI
    full_text: This is the complete message that we want the pepper robot to say. # This will be the spoken message
  -
    short: Hello
    full_text: Hello, Im pepper.
  -
    short: Insult
    full_text: Here are the test results; you are a horrible person.
  -
    short: Blah
    full_text: blah blah blah blah blah, blah blah blah, blah.

image_root_location: "/static/imgs/"

images:
  - 
    title: Landscape
    file_name: landscape.jpg
  -
    title: Umea logo
    file_name: umea_logo.png
  -
    title: Arrow keys
    file_name: arrow_keys.png

audio_root_location: static/audio

audio_files:
  - 
    title: Cantina band
    location: https://www2.cs.uic.edu/~i101/SoundFiles/CantinaBand60.wav
  - 
    title: Pink Panther
    location: https://www2.cs.uic.edu/~i101/SoundFiles/PinkPanther60.wav
  -
    title: Star Wars
    location: https://www2.cs.uic.edu/~i101/SoundFiles/StarWars60.wav
  -
    title: Imperial March
    location: ImperialMarch60.wav
  -
    title: Elephant walking
    location: https://www2.cs.uic.edu/~i101/SoundFiles/BabyElephantWalk60.wav

