pepper_ips:  # Entry in dropdown menu will be create for every list item
  - 130.239.182.11  # pepper ip address, should be reachable from network where interface is hosted.
  - 192.168.10.2
  - 192.168.10.3
  - 192.168.10.4

camera_save_dir: record_imgs  # relative folder on host machine, images form camera feed will be saved here
audio_save_dir: /home/nao/ # absolute path on pepper robot, you'll have scp it from there yourself

# AUTONOMOUS LIFE SETTINGS
# Leave as empty string to not leave value as is on connection to robot
# values must be valid for respective set methods in naoqi API...
autonomous_life_config:
  autonomous_state: "solitary"
  tangential_collision: ""
  orthogonal_collision: ""
  blinking: False  # can interfere with manual eye control...
  basic_awareness: False  # gets enabled by default if pepper enters solitary or interactive state...
  engagement_mode: ""
  head_breathing: False  # I would advise always having this disabled, conflicts with manual head control...
  arms_breathing: True
  body_breathing: True
  legs_breathing: True
  # TODO: ADD listening/speaking movements

# ALL CONCRETE ACTIONS (BUTTONS IN THE UI) CAN GET THE "key_comb" FIELD.
# PROVIDING A LIST WILL BIND THE KEYS IN THAT LAST TO THE CONCRETE ACTION TO EXECUTE
# SPECIAL KEYS CAN BE: "ctrl", "shift", "alt" etc, full list here: https://craig.is/killing/mice#keys
# example flag: key_comb: ["ctrl", "1"]  <-- Binds Control + 1 keyboard shortcut to an action
# ARROW KEY MAY NOT BE USED, AS THEY ARE ALREADY IN USE TO DRIVE PEPPER AND CONTROL THE HEAD AND HIP!!

images:
  -
    title: Default img
    file_name: climate_change.jpg
    is_default_img: True  # image with this flag will be displayed on connect
    key_comb: ["ctrl", "shift", 1]  # example for more complex shortcut
  - 
    title: Landscape
    file_name: landscape.jpg
    key_comb: ["ctrl", "shift", 2]
  -
    title: Umea logo
    file_name: umea_logo.png
    key_comb: ["ctrl", "shift", 3]
  -
    title: Arrow keys
    file_name: arrow_keys.png
    key_comb: ["ctrl", "shift", 4]
  - 
    title: Sound playing
    file_name: sound_playing.png
    key_comb: ["ctrl", "shift", 5]

image_root_location: /static/imgs/  # place image files here, on host machine

animated_speech:
    # Avoid special characters in messages, this can break the backend.
    # EG: Instead if a ', put &apos; into the message, which is the HTML symbol for the apostroph
  -
    title: Plain  # This will be shown in the GUI
    string: "This is just a simple message, no animations, no tags or annotations added."  # message pepper will say
    tooltip: "This is just a simple message, no animations, no tags or annotations added."  # tooltip for the button in UI
    key_comb: ["ctrl", "1"]  # keyboard shortcut for this action
  - 
    title: Pitch annotation
    string: "This is a message where we \\vct=150\\ change the pitch halfway through."
    tooltip: "This is a message where we \\vct=150\\ change the pitch halfway through."
    key_comb: ["ctrl", "2"]
  -
    title: Speed annotation
    string: "This is a message where we \\rspd=50\\ change the speed halfway through."
    tooltip: "This is a message where we \\rspd=50\\ change the speed halfway through."
    key_comb: ["ctrl", "3"]
  -
    title: Speech and animation
    string: "Hello there! ^start(animations/Stand/Gestures/Hey_1) I am over here. ^wait(animations/Stand/Gestures/Hey_1)"
    tooltip: "Hello there! ^start(animations/Stand/Gestures/Hey_1) I am over here. ^wait(animations/Stand/Gestures/Hey_1)"
    key_comb: ["ctrl", "4"]
  -
    title: Suspended speech
    string: "Look at me! ^run(animations/Stand/Gestures/ShowSky_8) I am this tall!"
    tooltip: "Look at me! ^run(animations/Stand/Gestures/ShowSky_8) I am this tall!"
    key_comb: ["ctrl", "5"]
  -
    title: Show tablet
    string: "^start(animations/Stand/Gestures/ShowTablet_3) Look at my tablet. ^wait(animations/Stand/Gestures/ShowTablet_3)"
    tooltip: "^start(animations/Stand/Gestures/ShowTablet_3) Look at my tablet. ^wait(animations/Stand/Gestures/ShowTablet_3)"
    key_comb: ["ctrl", "6"]
  -
    title: Long sequence
    string: "^start(animations/Stand/Gestures/Hey_1) Look over here. ^wait(animations/Stand/Gestures/Hey_1) I think ^start(animations/Stand/Waiting/ShowSky_1) there is a plane in the sky! ^wait(animations/Stand/Waiting/ShowSky_1)"
    tooltip: "^start(animations/Stand/Gestures/ShowTablet_3) Look over here. ^wait(animations/Stand/Gestures/ShowTablet_3)"
    # key_comb: ["ctrl", "7"]  # this is an example where we don't assign a keyboard shortcut

volume: 0.5  # range: [0.0 - 1.0], default = 1
voice_speed: 100  # range [50 - 400], default = 100
voice_pitch: 1 # range [1.0 - 4.0], default = 1, 0 disables effect

audio_files:
  # These have to be stored directly on the Pepper, it's the only way properly supported by the naoqi API :/
  # Button will be created for every item in the list
  -
    title: Imperial March  # This will be shown in the GUI
    location: /home/nao/sound_files/ImperialMarch60.wav  # absolute path on the Pepper
    key_comb: ["alt", "1"]
  - 
    title: Cantina band
    location: /home/nao/sound_files/CantinaBand60.wav
    key_comb: ["alt", "2"]
  -
    title: Star Wars
    location: /home/nao/sound_files/StarWars60.wav
    key_comb: ["alt", "3"]
  - 
    title: Pink Panther
    location: /home/nao/sound_files/PinkPanther60.wav
    key_comb: ["alt", "4"]
  -
    title: Elephant walking
    location: /home/nao/sound_files/BabyElephantWalk60.wav
    key_comb: ["alt", "5"]

gestures: # Buttons will be created for every item in the list
  -
    title: "Yes"  # This will be shown in the GUI
    gesture: "animations/Stand/Gestures/Yes_1"  # Gesture to execute
    tooltip: "Yes_1 gesture"  # Tooltip for buton
    key_comb: ["shift", "1"]
  -
    title: "No"
    gesture: "animations/Stand/Gestures/No_1"
    tooltip: "No_1 gesture"
    key_comb: ["shift", "2"]

  -
    title: "Wave"
    gesture: "animations/Stand/Gestures/Hey_3"
    tooltip: blah
    key_comb: ["shift", "3"]

  -
    title: "Me"
    gesture: "animations/Stand/Gestures/Me_1"
    tooltip: blah
    key_comb: ["shift", "4"]

  -
    title: "You"
    gesture: "animations/Stand/Gestures/You_1"
    tooltip: blah
    key_comb: ["shift", "5"]

  -
    title: "Embarrassed"
    gesture: "animations/Stand/Emotions/Neutral/Embarrassed_1"
    tooltip: blah
    key_comb: ["shift", "6"]

  -
    title: "Happy"
    gesture: "animations/Stand/Emotions/Positive/Happy_4"
    tooltip: blah
    key_comb: ["shift", "7"]

colors:
  -
    title: Red
    red: 1.0
    green: 0
    blue: 0
  -
    title: Yellow
    red: 1.0
    green: 1.0
    blue: 0
  -
    title: Orange
    red: 1.0
    green: 0.7
    blue: 0
  -
    title: Green
    red: 0
    green: 1.0
    blue: 0
  -
    title: Aqua
    red: 0
    green: 1.0
    blue: 1.0
  -
    title: Blue
    red: 0
    green: 0
    blue: 1.0
  -
    title: Magenta
    red: 1.0
    green: 0
    blue: 1.0
  -
    title: White
    red: 1.0
    green: 1.0
    blue: 1.0


# LED SETTINGS
# Putting empty strings as values leave the settings as is on connect
led_settings:
  intensity: 0.1
  color: # color for eye leds. API requires rgb values in range [0-1]
    red: 0
    green: 1.0
    blue: 0